### ISSUE TITLE
spatial interop

### ISSUE THREAD

**Issue by mdsumner** [EhrmannS/geometr#2]
I very much appreciate the language you use in this package

> that produce an identical output for the same metadata of different classes 

In [silicate](https://github.com/hypertidy/silicate#overview) we have models (SC, PATH, SC0) to store various more general forms of vector data (as paths vs. edges) and use general getter functions (sc_coord, sc_vertex, sc_object, ...) to obtain the underlying components, which sounds to me like your getters. The getter functions are more important even than the models because they aim to work on other spatial types. 

My idea was that getters could be defined by specialist packages (sf, spatstat, etc.) that know how to work in-situ on their kinds, and the models simply run the generic to get those components. Perhaps we can explore the common ideas we have here?

**Comment by EhrmannS** [comment]
Hi Michael,
thanks for your interest in my work! Seems like we agree that simple features are not the end of GI development and we both recognise the need of standardised getters and setters.

However, part of interoperability is that the functions do not only represent information in the same way but also that the functions can be called in the same way, which includes the name of the function. S4 generics/methods are an awesome tool to achieve that. I would argue that eventually, we need a central package, which harmonises the output (or input for that matter) for all geometric/spatial classes because let's be honest, there are plenty of package curators out there that would not agree to call their functions according to something some consortium has agreed upon, or to even make a method out of it in the first place. The current recommendation to label all functions with some package-specific prefix, such as `gt_*` or `sc_*` complicates this even further. Most packages have getters (and setters) in one way or the other already included and `geometr` mostly just makes use of the functions/methods that are standard in the respective package, to re-format the output into interoperable quality. Those functions are basically wrappers around what the specialist packages have defined.

What thoughts did you have on that? I have to say that it is a matter of days or weeks before I wanted to submit it to CRAN, refining the vignette atm to get the rationale proper and then I am mostly set.

**Comment by mdsumner** [comment]
I agree one language in a central package is required, but the candidate I see is terra as it takes over from raster - it has mostly all the right function names and some kind of guaranteed stability to that. But no getter/setter idioms.

I will pay heed to what you said here when I can explore geometr more, thanks for the reply.

**Comment by EhrmannS** [comment]
Not sure what you mean, do raster or terra intend to implement interoperability beyond providing their functions as methods? Why not sf? I don't see their agency in that, tbh.
